"""new initial migration

Revision ID: 6830e02d17d1
Revises: 
Create Date: 2021-11-18 11:55:57.210400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6830e02d17d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flasklogin-users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('keyboards',
    sa.Column('keyboard_id', sa.Integer(), nullable=False),
    sa.Column('keyboard_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('keyboard_id'),
    sa.UniqueConstraint('keyboard_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyboards')
    op.drop_table('flasklogin-users')
    # ### end Alembic commands ###
