"""empty message

Revision ID: baecc9c49ca6
Revises: 16129554d624
Create Date: 2021-11-18 18:17:02.470501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baecc9c49ca6'
down_revision = '16129554d624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyboards', sa.Column('cost', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyboards', 'cost')
    # ### end Alembic commands ###
